services:
  postgres:
    image: postgres:15-alpine
    container_name: postgres-bus
    environment:
      POSTGRES_DB: bus_tracker
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "123456"
    ports:
      - "5432:5432"

  redis:
    image: redis:7-alpine
    container_name: redis-bus
    ports:
      - "6379:6379"

  app:
    build: .
    container_name: bus-tracker-app
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - redis
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/bus_tracker
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: "123456"
      SPRING_DATA_REDIS_HOST: redis
